spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        SMTP:
          trust: "*"
        auth: true
        STARTTLS:
          enabled: true
        connection timeout: 5000
        timeout: 3000
        write timeout: 5000
application:
  security:
    jwt:
      secret-key: Abhinav
      expiration: 8640000