spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
application:
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088